haskell-distributed/network-transport-tcp

src/Network/Transport/TCP.hs

@mboes points out that it is less surprising to the user if we use the same defaults as the TCP layer, which I think makes sense.

Change tcpNoDelay default to be the same as TCP_NODELAY.

---

network-transport-tcp.cabal

Removes usage of deprecated fields

Rename extensions to default-extensions

---

network-transport-tcp.cabal
tests/TestTCP.hs

Currently we need TCP_USER_TIMEOUT support to be enabled in
network package. So increasing minimal bound.

Increase lower bound to network package.

---

src/Network/Transport/TCP.hs
tests/TestTCP.hs

Keepalive solved my problem where peers communicate over vpn connection (which sometimes reset due to connectivity problems but application layer doesn't get any notice about the failure hence sockets stuck on ESTABLISHED state on listening side).

Add TCP_KEEPALIVE support for sockets.

---

network-transport-tcp.cabal
src/Network/Transport/TCP.hs
tests/TestTCP.hs

Abstracted the use of `Chan`/`readChan`/`writeChan` so that we can give more complicated queueing and buffering policies.

Queueing and buffering for an EndPoint

---

network-transport-tcp.cabal
src/Network/Transport/TCP.hs
src/Network/Transport/TCP/Internal.hs
tests/TestTCP.hs

This patch eliminates the use of signed integers and
makes the text more explicit about what is being decoded from the wire.
`recvInt32` is not so clear about this: it would in fact receive a `Word32`
almost always, except in the case of control headers and connection
request responses, which would read a signed `Int` and pass it to
`tryToEnum` (`recvInt32` actually receives any `Num` type).
Similar story for encoding: `encodeInt32` would acutally encode any
`Enum` by using `fromEnum` and encoding the signed `Int`, but now
we encode a `Word32` explicitly.
Haddock says that `Int` is only guaranteed to have range
`[-2^29, 2^29 - 1]`. But `LightweightConnectionId = Word32` so we could
have a problem in `handleIncomingMessages`: the peer could give a valid
connection id which is interpreted …

Explicitly use Word32, avoid use of Enum

---

src/Network/Transport/TCP.hs
src/Network/Transport/TCP/Internal.hs
tests/TestTCP.hs

A transport has two optional limits:
- Address length: refuse to read peer addresses longer than this many bytes.
- Receive length: refuse to read data from a peer longer than this many bytes.
If a peer attempts to send an address of length exceeding the limit, the connection will be refused (socket will close).
If a peer attempts to send data on a lightweight connection exceeding the limit, the heavyweight connection which carries that lightweight connection will go down. The peer and the local node will get an `EventConnectionLost`.
A test case is included.
Some changes in here are also present in #51. Will resolves conflicts once either of them is merged.

Optional limits on address and data length

---

src/Network/Transport/TCP.hs
src/Network/Transport/TCP/Internal.hs

@dcoutts noticed that this is unacceptable. network-transport requires
that if `bss` is sent, then the receiver must get `Received _ bss'`
such that
concat bss = concat bss'
Splitting up the `Received` events therefore just can't be done. To
limit these, you have to use the global limit `tcpMaxReceiveLength`.

Remove maximum Received event size limit

---

src/Network/Transport/TCP.hs
src/Network/Transport/TCP/Internal.hs
tests/TestTCP.hs

When testing components built atop network-transport-tcp, it's sometimes
desirable to have a test case create an end point at the beginning of
the test and close it at the end, where all test cases share the same
transport. If we run such a test repeatedly, as is the typical style
when quick-checking, for instance, then we risk undefined behaviour: when
the next test case runs, the end point from the previous test case,
although closed, may still be receiving on one of its sockets. The
sockets have all been closed, their file-descriptors freed up, and so we
get undefined behaviour. This can be catastrophic: the stray thread can
steal `recv`s from the next end point's sockets, completely breaking the
protocol and for instance causing the end point to receive an incorrect
length prefix. …

apiCloseEndPoint blocks until no longer reciving

---

src/Network/Transport/TCP.hs

Given a pair of endpoints, each of them knows
- The latest locally-created connection identifier (outbound connection)
- The latest observed remotely-created connection identifier (inbound)
In order to close the socket, the peers must agree on these: locally-
created of A must match remotely-created of B, and remotely-created of A
must match locally-created of B.
When A sends CloseSocket, it can be sure that when it reaches B, B will
have seen all of A's locally-created connections (property of TCP), so
locally-created of A certainly matches remotely-created of B. To verify
the other half, A sends its latest observed remotely-created connection
identifier, and B just has to check that it matches its latest
locally-created identifier. There's no need to use ordering, equality
is enough. …

Use equality rather than ordering in socket close

---

src/Network/Transport/TCP.hs

New connections will time out if the peer does not send the required handshake
data promptly, i.e. an `EndPointId` followed by an `EndPointAddress`.
The `transportConnectTimeout` parameter from `TCPParameters` is re-used here,
but maybe a new parameter should be defined.

Time out new socket connections

---

src/Network/Transport/TCP.hs
tests/TestTCP.hs

It's possible that handleIncomingMessages is run when the remote
endpoint has already failed or been closed. These cases are in fact
premature exits, and in the case of a failure, ConnectionLost must be
enqueued. An example case: connect and send bottom. The value may be
evaluated before handleIncomingMessages (run in a separate thread)
begins to receive on the socket, and so the event may be skipped, and
the testSendException case from network-transport-tests will timeout.

prematureExit if EndPoint is closed or failed

---

src/Network/Transport/TCP.hs
src/Network/Transport/TCP/Internal.hs
tests/TestTCP.hs

This is to prevent a peer from denying service to another peer by lying
about their end point address. The attacker would give the address
of the victim and then simply hold that heavyweight connection open, so
that requests by the victim would be rejected as crossed connections.

Check peer-reported host against socket host

---

network-transport-tcp.cabal
src/Network/Transport/TCP.hs
src/Network/Transport/TCP/Internal.hs
tests/TestTCP.hs

A candidate implementation of protocol versioning. Here's how it works:
Versionless part of the protocol:
- When `A` connects to `B` it always sends a `Word32` version identifier
followed by a `Word32` giving the length of remaining data (presumably
version-specific handshake data).
- `B` can request a different version by sending
`ConnectionRequestUnsupportedVersion` followed by a `Word32`
indicating the version which `B` would prefer to use. Since it has the
length of the remaining data, it can then read and discard the rest of
the data sent by `A`.
- `A` can try again using `B`'s preferred version, or abandon the
connection if it doesn't support that version.
If `B` accepts the version number, then the rest of the interaction
proceeds according to that version.
Currently there is only …

Protocol versioning (feature request with potential implementation)

---

src/Network/Transport/TCP.hs

Prior to this patch, the connection timeout was misplaced and
effectively was a connection time limit instead.
```Haskell
{-# LANGUAGE OverloadedStrings #-}
import Network.Transport
import qualified Network.Transport.TCP as TCP
import Control.Concurrent
main = do
let timeout = 1000000
let params = TCP.defaultTCPParameters { TCP.transportConnectTimeout = Just timeout }
Right transport <- TCP.createTransport "127.0.0.1" "7777" ((,) "127.0.0.1") params
Right server <- newEndPoint transport
Right client <- newEndPoint transport
Right conn <- connect client (address server) ReliableOrdered defaultConnectHints
threadDelay (timeout * 2)
-- This ought to be 'Right ()' but the timeout has almost certainly killed the socket
-- by now.
-- err = TransportError SendFailed "user error (recvExact: …
```

Connection timeout only for setup phase

---

src/Network/Transport/TCP.hs

The server need not crash if `accept` throws an exception.
One example application: if the exception is EMFILE (no more file descriptors available), the server doesn't have to crash, it could just wait before trying to accept again.

Server exception handler is a parameter

---

network-transport-tcp.cabal
src/Network/Transport/TCP.hs
src/Network/Transport/TCP/Internal.hs
tests/TestTCP.hs

This makes it feasible to run a transport on a machine that isn't addressable from the network in which its peers live. Endpoints on this transport can connect to the addressable peers, but the peers can only connect to that endpoint if there's already a socket opened. Endpoints on the same unaddressable transport cannot connect to each-other, even though it's technically possible.
Unaddressable endpoints are given (random) UUIDv4 addresses. When an addressable endpoint receives a connection from an unaddressable peer, it generates one to identify that peer *locally* (highly unlikely that any other peer would make sense of that address). This is the address found on the `ConnectionOpened` event.
The connection request protocol (for the socket, not for lightweight connections) is changed: …

Unaddressable transports/endpoints (behind NAT, for instance)

---

network-transport-tcp.cabal

It seems that github issues are now used rather than [atlassian](https://cloud-haskell.atlassian.net), this PR updates the cabal file.

Update cabal bug-reports

---

ChangeLog
src/Network/Transport/TCP.hs

It is possible that the ConnectionRequestCrossed message may
never come from the other side, so we should unblock the endless
waiting on the "crossed" MVar in this case.

Fix possible endless waiting on the 'crossed' MVar

---

network-transport-tcp.cabal

We allow latest async package, so n-t-tcp will be buildable under
ghc-8.6.5.

Loosen async dependency.

---

.travis.yml
src/Network/Transport/TCP/Internal.hs

This package uses the old name for Data.ByteString.Builder, resulting in build failures for distributed-process on Stackage nightly.

Fix deprecated module name
